# Максимальное количество жизней игрока
lives: 2

# Время бана в секундах (например, 43200 секунд = 12 часов)
ban-time: 43200

# Сообщение, которое отправляется игроку при бане
death-message: "Вы умерли максимальное количество раз :("

# Время восстановления дополнительной жизни в секундах (например, 86400 секунд = 24 часа)
recovery-time: 43200

